### ISSUE TITLE
Addressing Feedback

### ISSUE THREAD

**Issue by bclue** [CMPUT301W19T21/PagePal#33]
Have a place in the wiki where we list how we addressed the feedback from part 2.

**Comment by bclue** [comment]
I'm assigning myself to this re: UI, but if everyone else also adds information about what they changed, that would be great!

**Comment by tchell** [comment]
I've added a section, feel free to add things.

**Comment by bclue** [comment]
Closing this issue as we have filled out that section and gotten marks back for it
